apiVersion: kustomize.config.k8s.io/v1beta1
bases:
- base
configMapGenerator:
- behavior: merge
  env: overlays/istio/params.env
  name: dex-parameters
configurations:
- overlays/istio/params.yaml
generatorOptions:
  disableNameSuffixHash: true
kind: Kustomization
namespace: auth
resources:
- overlays/istio/virtual-service.yaml
vars:
- fieldref:
    fieldPath: data.namespace
  name: namespace
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: dex-parameters
